/glg4debug/glg4param omit_muon_processes  1.0
/glg4debug/glg4param omit_hadronic_processes 1.0 


/tracking/verbose 0
/event/verbose 0

/tracking/storeTrajectory 1
/tracking/discardParticleTrajectory opticalphoton  

#/rat/db/set DETECTOR experiment "abat"
#/rat/db/set DETECTOR geo_file "abat/abat.geo"

/rat/db/set DETECTOR experiment "Watchmanabat"
/rat/db/set DETECTOR geo_file "Watchmanabat/Watchman.geo"


/run/initialize

##### Cherenkov
/process/activate Cerenkov all
/glg4scint/off   
/glg4scint/reemission off

# BEGIN EVENT LOOP
#/rat/proc lesssimpledaq
#/rat/proc fitbonsai
/rat/proc fitcentroid
/rat/proc fitpath

/rat/proc simpledaq
/rat/proc count
/rat/procset update 10

/rat/proc prune
/rat/procset prune "mc.track:opticalphoton"

# Use IO.default_output_filename
/rat/proclast outroot
/rat/procset file "neutron_3m3m_174pmt_wbls_Cherenkov.root"
#END EVENT LOOP

/generator/add combo gun2:regexfill:poisson
/generator/vtx/set neutron  0 0 0 0 0.001 0.20

#/generator/vtx/set 0 0 1.0
/generator/pos/set detector+

/run/beamOn 100000
